### ISSUE TITLE
Add message cancelling

### ISSUE THREAD

**Issue by glihm** [ArkProjectNFTs/bridge#142]
When sending a message to L1 -> L2, if for any reason there is an error in the reception contract, one surely want to get his assets back.

For that starknet has implemented a [cancellation strategy](https://docs.starknet.io/documentation/architecture_and_concepts/L1-L2_Communication/messaging-mechanism/#l2-l1_message_cancellation), which has it's protection mechanism.

The work associated with this issue must expose a new function in the L1 Starklane Bridge contract to handle the cancellation process (starting it and then validate the cancel after the delay).

**Comment by Gathin23** [comment]
I would like to take up this issue! Could you please explain me what should I be doing as this is my first contribution

**Comment by glihm** [comment]
Hello @Gathin23! Thank you for you will to contribute! :rocket:

I don't know how familiar you are with Starknet, but here you go. Technically speaking, the cancelling is simple:

1. Check this [documentation](https://docs.starknet.io/documentation/architecture_and_concepts/Network_Architecture/L1-L2_Communication/messaging-mechanism/#l2-l1_message_cancellation) about how messaging works, and this [README](https://github.com/TheArkProjekt/Starklane/blob/dev/apps/blockchain/README.md#request-protocol) about the protocol.
2. You will need to implement 2 external functions, one for starting the cancellation, one for cancelling after the period of wait. The bridge already has a reference to the Starknet Core Contract.
3. When the cancel is available, you have to check the tokens inside the request that is inside the message being cancelled to get them back to their owner. As you will see, for both calls the payload of the message contains the request, so we have all the information.

This is all for the technical part.

But we need to fix one more thing, that can be an other issue.
As messaging is asynchronous (L1 contract does not have feedback about the correct execution of the message on L2), we can't know if the message execution on L2 failed. We have to use an indexer/oracle service for that.
In this scenario, your first external function to start the cancelling, will query the oracle to ensure that the message is actually cancellable.

But let's keep this issue for the technical smart contract part for now if you agree. :+1:

Let me know if you have any other doubts.

**Comment by Gathin23** [comment]
Will give it a shot and let you know

**Comment by Gathin23** [comment]
Hey @gilhm I have forked it and did yarn build in the local machine, Could you help me on which file i should make the change and how should i test its working.

Its my first time working on a projects issue so this help of getting me to learn how to contribute from you would be a great value to me! Thanks in advance :)

**Comment by glihm** [comment]
Sorry for now the front end is not yet connected so you shouldn't use yarn.

In the context of your issue using forge in the ethereum repository should work fine. You can find the tests folder with already available tests.

`forge test` being in the ethereum folder.

**Comment by Gathin23** [comment]
Got it Will work on it now!!

**Comment by Gathin23** [comment]
Which is the contract that i should implement the change in and how should i be testing it

**Comment by glihm** [comment]
You should implement the logic into the `Bridge.sol` file.
Also, to test the code as presented in the README and Makefiles, you should use [foundry](https://book.getfoundry.sh/forge/writing-tests). :+1:

**Comment by Gathin23** [comment]
I have did this implementation in the code and its compiling properly but i am not sure on how to write the test for it

```
mapping(bytes32 => uint256) private l1ToL2Messages;
    mapping(bytes32 => uint256) private l1ToL2MessageCancellations;
    uint256 private messageCancellationDelay = 86400; 

    // Event to notify when message cancellation is started
    event MessageToL2CancellationStarted(
        address indexed sender,
        uint256 indexed toAddress,
        uint256 selector,
        uint256[] payload,
        uint256 nonce
    );

    // Event to notify when message cancellation is completed
    event MessageToL2Canceled(
        address indexed sender,
        uint256 indexed toAddress,
        uint256 selector,
        uint256[] payload,
        uint256 nonce
    );

    function getL1ToL2MsgHash(
    uint256 toAddress,
    uint256 selector,
    uint256[] calldata payload,
    uint256 nonce
) internal pure returns (bytes32) {
    return keccak256(abi.encodePacked(toAddress, selector, payload, nonce));
}


    function startL1ToL2MessageCancellation(
        uint256 toAddress,
        uint256 selector,
        uint256[] calldata payload,
        uint256 nonce
    ) external {
        emit MessageToL2CancellationStarted(msg.sender, toAddress, selector, payload, nonce);
        bytes32 msgHash = getL1ToL2MsgHash(toAddress, selector, payload, nonce);
        uint256 msgCount = l1ToL2Messages[msgHash];
        require(msgCount > 0, "NO_MESSAGE_TO_CANCEL");
        l1ToL2MessageCancellations[msgHash] = block.timestamp;
    }

    function cancelL1ToL2Message(
        uint256 toAddress,
        uint256 selector,
        uint256[] calldata payload,
        uint256 nonce
    ) external {
        emit MessageToL2Canceled(msg.sender, toAddress, selector, payload, nonce);
        bytes32 msgHash = getL1ToL2MsgHash(toAddress, selector, payload, nonce);
        uint256 msgCount = l1ToL2Messages[msgHash];
        require(msgCount > 0, "NO_MESSAGE_TO_CANCEL");

        uint256 requestTime = l1ToL2MessageCancellations[msgHash];
        require(requestTime != 0, "MESSAGE_CANCELLATION_NOT_REQUESTED");

        uint256 cancelAllowedTime = requestTime + messageCancellationDelay;
        require(cancelAllowedTime >= requestTime, "CANCEL_ALLOWED_TIME_OVERFLOW");
        require(block.timestamp >= cancelAllowedTime, "MESSAGE_CANCELLATION_NOT_ALLOWED_YET");

        l1ToL2Messages[msgHash] = msgCount - 1;
    }
```

**Comment by glihm** [comment]
Hello! Could you please use the [GitHub flow](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request?tool=webui):

1. Clone the repo locally on your machine.
2. Create a branch and do your modification.
3. Push a PR on the repository.

Thank you!

**Comment by Gathin23** [comment]
Hey so shall i give a pull request without test cases?
