### ISSUE TITLE
Implement burn logic

### ISSUE THREAD

**Issue by glihm** [ArkProjectNFTs/bridge#144]
At this moment, the Starklane bridge only use the escrow strategy. When a token is deposited, it's put into escrow before the message can reach the other chain.

In some configuration, one also wants to burn a token once the bridge request is successfully processed on the destination chain.

**However**, burning the token in a synchronous manner instead of putting the token in escrow is too dangerous.
For this concern, when someone deposit a token with the `burn` flag enabled, a transaction must then be possible on Starklane Bridge contract to effectively burn the token (which is in escrow at this moment).

In this work, you should implement the burn logic in the bridge, ensuring that:
1. The request containing the token is effectively allowing the burn.
2. Ensuring the collection authorizes the bridge to burn a token.
3. Burn all the tokens related to the request.

**Comment by Dannyswiss1** [comment]
hello, can I work on this project?
