### ISSUE TITLE
Implement multi-document ACID transactions for MongoStore

### ISSUE THREAD

**Issue by glihm** [ArkProjectNFTs/bridge#150]
The indexer for now is not using any transaction (only at document level).

To ensure that a block is fully indexed, or nothing is saved, a transaction must be started for the store in use (for now it's `MongoStore`) during all operation on a block.

The transaction must include:

1. All the operations done during the loop on the events/log of a block.
2. The insertion of the block index to ensure that all events processing + the block index are updated at one.

Relevant code:
* Example of the location on [starknet indexer](https://github.com/TheArkProjekt/Starklane/blob/dev/apps/indexer/src/starknet_indexer/indexer.rs#L137).
* Mongo rust driver - [transactions](https://www.mongodb.com/docs/manual/core/transactions/#transactions-api).

**Comment by mubarak23** [comment]
@glihm i will like to handle this issue, kindly assign this issue to me
