### ISSUE TITLE
Integrate Starknet ID in the app 

### ISSUE THREAD

**Issue by fricoben** [ArkProjectNFTs/bridge#217]
## Description

Following [these](https://lfg-labs.notion.site/Ark-integration-389b0bca99b144f7b5a487fe58e6704e) recommendations made by the Starknet ID team and @remiroyc approval. 

We can integrate stark domains in the app (or update the integration that was previously made).

**Comment by AnoukRImola** [comment]
Hello guys! Is this issue open to contributions? And if so, can I take it?
