### ISSUE TITLE
withdraw_auto_from_l1 escrow is not zeroed

### ISSUE THREAD

**Issue by ptisserand** [ArkProjectNFTs/bridge#226]
From https://codehawks.cyfrin.io/c/2024-07-ark-project/s/177

L2 escrow is not reset when withdrawn.

## details
When tokens are deposited on L2 via `deposit_tokens()`, they will be deposited in the `escrow` mapping, so when someone transfers back the same NFTs from L1 → L2 to take it from the contract balance, because they already exist.

But when they are transferred back to L2, `withdraw_auto_from_l1()` transfers them if they exist in the `escrow` mapping, but never resets the mapping when transferring it, this creates confusion that the tokens are still in the `bridge.cairo` contract.

Unit test must be provided.

**Comment by od-hunter** [comment]
Hi @ptisserand , please can I be assigned this when od hack starts tomorrow?

**Comment by mubarak23** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
I am a Experience Cairo smart contract developer with experience working on projects such as Just Art Peace, Dojo, Kart, TBA, and Shinigami. Before transitioning to Cairo development, I was a backend developer specializing in Rust.



My recent work with cairo starknet
- https://github.com/keep-starknet-strange/raito/pull/128
- https://github.com/keep-starknet-strange/raito/pull/143
- https://github.com/horuslabsio/TBA/pull/45
- https://github.com/horuslabsio/karst-core/pull/60
- https://github.com/keep-starknet-strange/art-peace/pull/121
- https://github.com/keep-starknet-strange/zkramp/pull/33
- https://github.com/keep-starknet-strange/art-peace/pull/32
- https://github.com/horuslabsio/TBA/pull/53



My recent work with rust
- https://github.com/mubarak23/axum-user-auth
- https://github.com/antoyo/rustc_codegen_gcc/pull/1
- https://github.com/antoyo/rustc_codegen_gcc/pull/5
- https://github.com/fedimint/fedimint/pull/5994
- https://github.com/mubarak23/soroban-bank


### How I plan on tackling this issue
As issue describe

Am going to reset the mapping to zero once the withdrawal is handle

ETH: 15HRS

**Comment by od-hunter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
Please can I be assigned this issue? This is my first time applying in this ecosystem and I’d love to be given the opportunity. I am a blockchain Developer, and my experience includes html, css, react, JavaScript,TypeScript and solidity, python and Cairo.

### How I plan on tackling this issue
To solve this issue, I'd take the following steps:

1.⁠ ⁠I’ll update withdraw_auto_from_l1() (add logic to reset the escrow mapping after tokens are transferred, ensuring they are no longer recorded in the contract's state).
2.⁠ ⁠I’ll test that after depositing tokens, withdrawing them using withdraw_auto_from_l1() resets the escrow.
Validate the escrow mapping is cleared after the withdrawal.
3.⁠ ⁠I’ll ensure tests cover multiple scenarios to confirm the escrow is correctly reset in all cases.

Please assign me.

**Comment by od-hunter** [comment]
> The maintainer ptisserand has assigned od-hunter to this issue via [OnlyDust](https://app.onlydust.com/p/arkproject) Platform. Good luck!

Thank you ser🫡

**Comment by od-hunter** [comment]
> Hi @od-hunter any update on this ?

I’ve started working on it. Will push a pr soon
