### ISSUE TITLE
Missing Public Burn Function in `erc721_bridgeable.cairo` Limits Future Compatibility

### ISSUE THREAD

**Issue by ptisserand** [ArkProjectNFTs/bridge#229]
From https://codehawks.cyfrin.io/c/2024-07-ark-project/s/729

The `erc721_bridgeable.cairo` contract lacks a public burn function, which is essential for enabling token burning on Layer 2 (L2) in future updates, particularly with the planned useAutoBurn strategy.

**Comment by saimeunt** [comment]
@ptisserand Would love to work on this one, I have some experience in Cairo including ERC721Burnable logic 👌 
https://github.com/carbonable-labs/cairo-erc-7498/blob/main/src/erc7498/interface.cairo#L47-L49

**Comment by mubarak23** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
I am a Experience Cairo smart contract developer with experience working on projects such as Just Art Peace, Dojo, Kart, TBA, and Shinigami. Before transitioning to Cairo development, I was a backend developer specializing in Rust.



My recent work with cairo starknet
- https://github.com/keep-starknet-strange/raito/pull/128
- https://github.com/keep-starknet-strange/raito/pull/143
- https://github.com/horuslabsio/TBA/pull/45
- https://github.com/horuslabsio/karst-core/pull/60
- https://github.com/keep-starknet-strange/art-peace/pull/121
- https://github.com/keep-starknet-strange/zkramp/pull/33
- https://github.com/keep-starknet-strange/art-peace/pull/32
- https://github.com/horuslabsio/TBA/pull/53



My recent work with rust
- https://github.com/mubarak23/axum-user-auth
- https://github.com/antoyo/rustc_codegen_gcc/pull/1
- https://github.com/antoyo/rustc_codegen_gcc/pull/5
- https://github.com/fedimint/fedimint/pull/5994
- https://github.com/mubarak23/soroban-bank


### How I plan on tackling this issue
AS the issue describe, am going to add a function that enable enabling token burning on Layer 2 and also write test case for the function sure it’s work as expected.

**Comment by raizo07** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
Hello I'll like to be assigned to work on this. 

I'm a software Dev with over four years experience and have worked on a couple of projects here. Here's a link to my profile https://app.onlydust.com/u/raizo07

**Comment by saimeunt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
Would love to work on this one, I have some experience in Cairo including ERC721Burnable logic 👌
https://github.com/carbonable-labs/cairo-erc-7498/blob/main/src/erc7498/interface.cairo#L47-L49

### How I plan on tackling this issue
I will implement a burn function on ERC721Bridgeable and provide all the necessary tests.

**Comment by ptisserand** [comment]
Closed by  #243
