### ISSUE TITLE
Admin won't be able to remove certain collections from the whitelist on L2

### ISSUE THREAD

**Issue by ptisserand** [ArkProjectNFTs/bridge#230]
From https://codehawks.cyfrin.io/c/2024-07-ark-project/s/124

Admin won't be able to remove collections from the whitelist on L2 in certain cases. The issue stems from the fact that there's a missing line in the `_white_list_collection` function in the `bridge.cairo` contract that will make the function loop indefinitely if the collection to be removed is after 2nd place in the linked list.

Removing a collection by an admin should always be possible. This will have an even bigger impact if a malicious collection finds its way into the whitelist either by accident or at a time that the whitelist has been off.

**Comment by ShantelPeters** [comment]
Hello @ptisserand please i will like to take up this issue by tomorrow kindly assign

**Comment by ikemHood** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
Hello, can i take on this.

ETA less than 24hrs

**Comment by JoE11-y** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
With over four years in blockchain and backend development, I’ve worked across different ecosystems, handling everything from smart contract design to on-chain interactions and protocol integration. I focus on building secure, scalable, and reliable blockchain applications, managing both on-chain and off-chain infrastructure.

### How I plan on tackling this issue
I'd start by reviewing the logic causing the issue, then explore alternative solutions to handle the removal of collections, then wrap up with thorough testing to ensure the fix works across different scenarios

**Comment by tevrat-aksoy** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
hello, I am cairo developer ith 2 years experience. I want to work on this issue.

**Comment by ptisserand** [comment]
Hi @JoE11-y any update on this ?

**Comment by JoE11-y** [comment]
Just did @ptisserand.
