### ISSUE TITLE
Add missing events emit in bridge.cairo

### ISSUE THREAD

**Issue by ptisserand** [ArkProjectNFTs/bridge#232]
The functions `enable_white_list`, `set_bridge_l1_addr`, `set_erc721_class_hash` and `set_l1_l2_collection_mapping` in `bridge.cairo` lacks of events emitting.

Unit test must be updated to add event check.

**Comment by PavitraAgarwal21** [comment]
@ptisserand love to take this up .

**Comment by saimeunt** [comment]
@ptisserand Would love to work on this one, I have some experience in Cairo including unit testing 👌 
https://github.com/carbonable-labs/cairo-erc-7498

**Comment by mubarak23** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
I am a Experience Cairo smart contract developer with experience working on projects such as Just Art Peace, Dojo, Kart, TBA, and Shinigami. Before transitioning to Cairo development, I was a backend developer specializing in Rust.



My recent work with cairo starknet
- https://github.com/keep-starknet-strange/raito/pull/128
- https://github.com/keep-starknet-strange/raito/pull/143
- https://github.com/horuslabsio/TBA/pull/45
- https://github.com/horuslabsio/karst-core/pull/60
- https://github.com/keep-starknet-strange/art-peace/pull/121
- https://github.com/keep-starknet-strange/zkramp/pull/33
- https://github.com/keep-starknet-strange/art-peace/pull/32
- https://github.com/horuslabsio/TBA/pull/53



My recent work with rust
- https://github.com/mubarak23/axum-user-auth
- https://github.com/antoyo/rustc_codegen_gcc/pull/1
- https://github.com/antoyo/rustc_codegen_gcc/pull/5
- https://github.com/fedimint/fedimint/pull/5994
- https://github.com/mubarak23/soroban-bank



### How I plan on tackling this issue
I will update the functions outline in the issue description with event and emit them, 

Then write unit test for event emitted in each of the function

**Comment by Gift-Naomi** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
Simplify core test file structure by moving tests in /src next to code

### How I plan on tackling this issue
1. Add event emissions to `enable_white_list`, `set_bridge_l1_addr`, `set_erc721_class_hash`, and `set_l1_l2_collection_mapping` in `bridge.cairo`.

2. Include relevant parameters in the events for tracking changes.

3. Update unit tests to verify the correct events are emitted with expected values.

**Comment by danielcdz** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
Hello, I'm Daniel Calderón!
I'm a passionate software engineer with over 3 years of experience, actively contributing to open-source projects through OnlyDust. I’m also a community moderator at Dojo Coding, where I help new developers get started with blockchain development.
Over the past few months, I've contributed to several Starknet projects, including cairo-vm-go by Nethermind. Currently, I’m a Cairo developer at ByteBuilders, working on ByteBeasts, a fully on-chain RPG game built using the Dojo Engine framework.
My expertise spans full-stack development, with a focus on backend, frontend, and smart contract development in blockchain ecosystems.




### How I plan on tackling this issue
I will use the starknet::testing utils to check if the events were emitted properly after applying the changes on the function

**Comment by aji70** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
i'm a solidity and cairo smart contract  developer with over 2 years experience and believe i have the skill set for the task 

### How I plan on tackling this issue
would create and add the missing events

**Comment by saimeunt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/arkproject).

### My background and how it can be leveraged
Would love to work on this one, I have some experience in Cairo including unit testing 👌
https://github.com/carbonable-labs/cairo-erc-7498

### How I plan on tackling this issue
I will make sure to emit the correct events and test that they were indeed emitted using snfoundry spy and assert_emitted.
